name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 172.31.252.17
          username: ayoubroot
          key:
          port: 22
          script: |
            cd /home/ayoubroot/spring-app
            rm -rf *
            scp -o StrictHostKeyChecking=no target/*.jar ayoubroot@172.31.252.17:/home/ayoubroot/spring-app/app.jar
            sudo systemctl restart helloworld.service